// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDbu4Pf_Ng4JWoPp7QnjLQ8lb7Us6cR6PU',
    appId: '1:816760214374:android:505321274784b016aa2ea7',
    messagingSenderId: '816760214374',
    projectId: 'autoschool-btgp-ddb89',
    storageBucket: 'autoschool-btgp-ddb89.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC6VzzfsxjCETDccOT_OgizJ9CG2_3HmVQ',
    appId: '1:816760214374:ios:6513c9745d8ae443aa2ea7',
    messagingSenderId: '816760214374',
    projectId: 'autoschool-btgp-ddb89',
    storageBucket: 'autoschool-btgp-ddb89.firebasestorage.app',
    androidClientId: '816760214374-116el507jgp9ov6s7op3fc3oa85f2hp0.apps.googleusercontent.com',
    iosClientId: '816760214374-8a4egmtggfhkauajnc1eq2ujuq2h403l.apps.googleusercontent.com',
    iosBundleId: 'com.example.autoschoolBtgp',
  );
}
